"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"
add_newline = true

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$python\
$cmd_duration
$character"""

[os]
disabled = false
format = '[](fg:mauve)[$symbol](bg:mauve fg:base)[](fg:mauve) '

[os.symbols]
Ubuntu = ""
Debian = ""
Linux = ""
Macos = ""
Windows = ""
Arch = ""
Alpine = ""
Fedora = ""
Redhat = ""

[username]
show_always = true
style_user = "bg:peach fg:base"
style_root = "bg:red fg:base bold"
format = '[](fg:peach)[ $user]($style)[](fg:peach) '

[directory]
format = '[](fg:yellow)[  $path](bg:yellow fg:base)[](fg:yellow) '
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"
read_only = " "
read_only_style = "bg:yellow fg:red"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~/work" = "󰒱 ~/work"

[git_branch]
symbol = ""
format = '[](fg:green)[$symbol $branch](bg:green fg:base)'

[git_status]
format = '[$all_status$ahead_behind](bg:green fg:base)[](fg:green) '
modified = " "
untracked = " "
stashed = " "
staged = " "
renamed = " »"
deleted = " "
conflicted = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[nodejs]
symbol = ""
format = '[](fg:teal)[ $symbol $version](bg:teal fg:base)[](fg:teal) '

[rust]
symbol = ""
format = '[](fg:teal)[ $symbol $version](bg:teal fg:base)[](fg:teal) '

[golang]
symbol = ""
format = '[](fg:teal)[ $symbol $version](bg:teal fg:base)[](fg:teal) '

[python]
symbol = ""
format = '[](fg:teal)[ $symbol $version](bg:teal fg:base)[](fg:teal) '

[cmd_duration]
min_time = 500
format = '[  $duration ](fg:overlay2)'

[character]
success_symbol = "[❯](bold fg:mauve)"
error_symbol = "[❯](bold fg:red)"
vicmd_symbol = "[❮](bold fg:green)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
silver = "#bac2de"
charcoal = "#585b70"
